### ISSUE TITLE
Support multiple rounds

### ISSUE THREAD

**Issue by daisyliu618** [ZacSweers/auto-service-ksp#105]
Hi we have been actively using auto-service-ksp in our repo and found below issue:

The AutoService code generator doesn't support KSP very well (for example 
The AutoService code generator doesn't process @AutoService  in code-generated UiRegistry). 

We believe below changes need to be made
https://kotlinlang.org/docs/ksp-multi-round.html#changes-to-your-processor

instead of returning an empty list here https://github.com/ZacSweers/auto-service-ksp/blob/main/processor/src/main/kotlin/dev/zacsweers/autoservice/ksp/AutoServiceSymbolProcessor.kt#L132

so it can support KSP correctly which is multi-round.

**Comment by ZacSweers** [comment]
Want to send a PR?
