### ISSUE TITLE
Plugin not working with latest kotlin version

### ISSUE THREAD

**Issue by sureshg** [ZacSweers/auto-service-ksp#28]
```kotlin
kotlin  = "1.6.10"
ksp = "1.6.10-1.0.2"
ksp-auto-service = "1.0.0"
```

Error,
```
> Cannot query the value of task ':kspKotlin' property 'classpathSnapshotProperties.classpathSnapshotDir' because it has no value available.
```
It seems like an issue with the old version of KSP this plugin depends on. Would it be possible to upgrade to the latest kotlin version?

**Comment by ZacSweers** [comment]
This is coming from gradle, which this processor doesn't have any involvement in. I suspect your build is somehow forcing an older version of the KSP gradle plugin

**Comment by sureshg** [comment]
Thanks. On further investigation, it seems to be triggered by the kotlin `incremental` compilation option. Working fine after removing this option. Sorry for the inconvenience 

```kotlin
  withType<KotlinCompile>().configureEach {
    kotlinOptions {
      verbose = true
      javaParameters = true
      incremental = true
```
