### ISSUE TITLE
Do not fail the build if `@AutoService` annotation is absent from compilation unit

### ISSUE THREAD

**Issue by JakeWharton** [ZacSweers/auto-service-ksp#30]
This prevents usage in the following form:
```kotlin
compileOnly(libs.autoService.annotations)
ksp(libs.autoService.ksp)
```
as the `testKsp` configuration extends from the `ksp` configuration and thus the processor will run over the test sources where the annotation is not present.

Now an easy workaround is to `testCompileOnly` the annotation, but I don't have anything annotated in that source set so it's a bit weird.

I don't think this is a problem for the main source set either. If you omit the annotation dependency accidentally you would be unable to annotate any types.

**Comment by ZacSweers** [comment]
Sounds reasonable to me. I can take a look next week unless you wanna send a PR before then

**Comment by JakeWharton** [comment]
Should be a two second fix of logger.error to logger.warn (or just deleting the log).

The question is whether you want to test it or not...

I'm already in a side project of a side project where I discovered this. Not sure I can push another onto the stack!

**Comment by JakeWharton** [comment]
Although I'm in NYC all week if you want to pair!

**Comment by ZacSweers** [comment]
Game, I'll message ya

**Comment by ZacSweers** [comment]
https://github.com/ZacSweers/auto-service-ksp/releases/tag/1.1.0
